export const FETCH_MESSAGES_REQUEST = "FETCH_MESSAGES_REQUEST";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILTURE = "FETCH_MESSAGES_FAILTURE";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILTURE = "SEND_MESSAGE_FAILTURE";

export const FETCH_CHAT_BY_PROJECT_REQUEST = "FETCH_CHAT_BY_PROJECT_REQUEST";
export const FETCH_CHAT_BY_PROJECT_SUCCESS = "FETCH_CHAT_BY_PROJECT_SUCCESS";
export const FETCH_CHAT_BY_PROJECT_FAILTURE = "FETCH_CHAT_BY_PROJECT_FAILTURE";

export const FETCH_CHAT_MESSAGE_REQUEST = "FETCH_CHAT_MESSAGE_REQUEST";
export const FETCH_CHAT_MESSAGE_SUCCESS = "FETCH_CHAT_MESSAGE_SUCCESS";
export const FETCH_CHAT_MESSAGE_FAILTURE = "FETCH_CHAT_MESSAGE_FAILTURE";


