export const GET_USER_SUBSCRIPTION_REQUEST = "GET_USER_SUBSCRIPTION_REQUEST";
export const GET_USER_SUBSCRIPTION_SUCCESS = "GET_USER_SUBSCRIPTION_SUCCESS";
export const GET_USER_SUBSCRIPTION_FAILURE = "GET_USER_SUBSCRIPTION_FAILURE";

export const UPDATE_SUBSCRIPTION_REQUEST = "UPDATE_SUBSCRIPTION_REQUEST";
export const UPDATE_SUBSCRIPTION_SUCCESS = "UPDATE_SUBSCRIPTION_SUCCESS";
export const UPDATE_SUBSCRIPTION_FAILURE = "UPDATE_SUBSCRIPTION_FAILURE";