export const FETCH_PROJECTS_REQUEST = "FETCH_PROJECTS_REQUEST";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAILTURE = "FETCH_PROJECTS_FAILTURE";

export const FETCH_PROJECT_BY_ID_REQUEST = "FETCH_PROJECT_BY_ID_REQUEST";
export const FETCH_PROJECT_BY_ID_SUCCESS = "FETCH_PROJECT_BY_ID_SUCCESS";
export const FETCH_PROJECT_BY_ID_FAILTURE = "FETCH_PROJECT_BY_ID_FAILTURE";

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILTURE = "CREATE_PROJECT_FAILTURE";

export const SEARCH_PROJECT_REQUEST = "SEARCH_PROJECT_REQUEST";
export const SEARCH_PROJECT_SUCCESS = "SEARCH_PROJECT_SUCCESS";
export const SEARCH_PROJECT_FAILTURE = "SEARCH_PROJECT_FAILTURE";

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILTURE = "DELETE_PROJECT_FAILTURE";

export const INVITE_TO_PROJECT_REQUEST = "INVITE_TO_PROJECT_REQUEST";
export const INVITE_TO_PROJECT_SUCCESS = "INVITE_TO_PROJECT_SUCCESS";
export const INVITE_TO_PROJECT_FAILTURE = "INVITE_TO_PROJECT_FAILTURE";

export const ACCEPT_INVITATION_REQUEST = "ACCEPT_INVITATION_REQUEST";
export const ACCEPT_INVITATION_SUCCESS = "ACCEPT_INVITATION_SUCCESS";
export const ACCEPT_INVITATION_FAILTURE = "ACCEPT_INVITATION_FAILTURE";